[advisories]
ignore = []
informational_warnings = ["unmaintained", "unsound", "notice"]
severity_threshold = "low"

[database]
path = "~/.cargo/advisory-db"
url = "https://github.com/RustSec/advisory-db.git"
fetch = true
stale = false

[output]
deny = []
format = "terminal"
quiet = false
show_tree = true

[yanked]
enabled = true
update_index = true
